package v1.service.minutmiljo.api.ecos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-10-20T15:30:01.996+02:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", name = "IMinutMiljoService")
@XmlSeeAlso({v1.datacontracts.minutmiljo.api.ecos.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, ObjectFactory.class})
public interface IMinutMiljoService {

    @WebMethod(operationName = "GetAccommodationTypes", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetAccommodationTypes")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetAccommodationTypes", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetAccommodationTypesResponse")
    @RequestWrapper(localName = "GetAccommodationTypes", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetAccommodationTypes")
    @ResponseWrapper(localName = "GetAccommodationTypesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetAccommodationTypesResponse")
    @WebResult(name = "GetAccommodationTypesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getAccommodationTypes()
;

    @WebMethod(operationName = "CreateOccurrenceOnCase", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateOccurrenceOnCase")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateOccurrenceOnCase", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateOccurrenceOnCaseResponse")
    @RequestWrapper(localName = "CreateOccurrenceOnCase", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateOccurrenceOnCase")
    @ResponseWrapper(localName = "CreateOccurrenceOnCaseResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateOccurrenceOnCaseResponse")
    @WebResult(name = "CreateOccurrenceOnCaseResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String createOccurrenceOnCase(

        @WebParam(name = "createOccurrenceOnCaseSvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.CreateOccurrenceOnCaseSvcDto createOccurrenceOnCaseSvcDto
    );

    @WebMethod(operationName = "GetDrySolutionCompostTypes", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDrySolutionCompostTypes")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDrySolutionCompostTypes", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDrySolutionCompostTypesResponse")
    @RequestWrapper(localName = "GetDrySolutionCompostTypes", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDrySolutionCompostTypes")
    @ResponseWrapper(localName = "GetDrySolutionCompostTypesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDrySolutionCompostTypesResponse")
    @WebResult(name = "GetDrySolutionCompostTypesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getDrySolutionCompostTypes()
;

    @WebMethod(operationName = "CreatePersonParty", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreatePersonParty")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreatePersonParty", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreatePersonPartyResponse")
    @RequestWrapper(localName = "CreatePersonParty", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreatePersonParty")
    @ResponseWrapper(localName = "CreatePersonPartyResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreatePersonPartyResponse")
    @WebResult(name = "CreatePersonPartyResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String createPersonParty(

        @WebParam(name = "personParty", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.PersonSvcDto personParty
    );

    @WebMethod(operationName = "CreateFoodFacility", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateFoodFacility")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateFoodFacility", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateFoodFacilityResponse")
    @RequestWrapper(localName = "CreateFoodFacility", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateFoodFacility")
    @ResponseWrapper(localName = "CreateFoodFacilityResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateFoodFacilityResponse")
    @WebResult(name = "CreateFoodFacilityResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String createFoodFacility(

        @WebParam(name = "createFoodFacilitySvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.CreateFoodFacilitySvcDto createFoodFacilitySvcDto
    );

    @WebMethod(operationName = "GetFoodFacilities", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetFoodFacilities")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetFoodFacilities", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetFoodFacilitiesResponse")
    @RequestWrapper(localName = "GetFoodFacilities", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetFoodFacilities")
    @ResponseWrapper(localName = "GetFoodFacilitiesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetFoodFacilitiesResponse")
    @WebResult(name = "GetFoodFacilitiesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfFoodFacilityInfoSvcDto getFoodFacilities(

        @WebParam(name = "request", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.GetFoodFacilitiesSvcDto request
    );

    @WebMethod(operationName = "GetRefrigerantUnitUsages", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetRefrigerantUnitUsages")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetRefrigerantUnitUsages", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetRefrigerantUnitUsagesResponse")
    @RequestWrapper(localName = "GetRefrigerantUnitUsages", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetRefrigerantUnitUsages")
    @ResponseWrapper(localName = "GetRefrigerantUnitUsagesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetRefrigerantUnitUsagesResponse")
    @WebResult(name = "GetRefrigerantUnitUsagesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getRefrigerantUnitUsages()
;

    @WebMethod(operationName = "GetCasePartyRoles", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetCasePartyRoles")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetCasePartyRoles", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetCasePartyRolesResponse")
    @RequestWrapper(localName = "GetCasePartyRoles", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetCasePartyRoles")
    @ResponseWrapper(localName = "GetCasePartyRolesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetCasePartyRolesResponse")
    @WebResult(name = "GetCasePartyRolesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfConnectedRoleSvcDto getCasePartyRoles(

        @WebParam(name = "caseId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String caseId
    );

    @WebMethod(operationName = "GetFacilityPartyRoles", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetFacilityPartyRoles")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetFacilityPartyRoles", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetFacilityPartyRolesResponse")
    @RequestWrapper(localName = "GetFacilityPartyRoles", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetFacilityPartyRoles")
    @ResponseWrapper(localName = "GetFacilityPartyRolesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetFacilityPartyRolesResponse")
    @WebResult(name = "GetFacilityPartyRolesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfConnectedRoleSvcDto getFacilityPartyRoles(

        @WebParam(name = "facilityId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String facilityId
    );

    @WebMethod(operationName = "CreateHeatPumpFacility", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateHeatPumpFacility")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateHeatPumpFacility", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateHeatPumpFacilityResponse")
    @RequestWrapper(localName = "CreateHeatPumpFacility", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateHeatPumpFacility")
    @ResponseWrapper(localName = "CreateHeatPumpFacilityResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateHeatPumpFacilityResponse")
    @WebResult(name = "CreateHeatPumpFacilityResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String createHeatPumpFacility(

        @WebParam(name = "createIndividualSewageSvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.CreateHeatPumpFacilitySvcDto createIndividualSewageSvcDto
    );

    @WebMethod(operationName = "AddPartyToFacility", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddPartyToFacility")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddPartyToFacility", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddPartyToFacilityResponse")
    @RequestWrapper(localName = "AddPartyToFacility", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddPartyToFacility")
    @ResponseWrapper(localName = "AddPartyToFacilityResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddPartyToFacilityResponse")
    public void addPartyToFacility(

        @WebParam(name = "model", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.AddPartyToFacilitySvcDto model
    );

    @WebMethod(operationName = "CanCreateHealthProtectionFacilityOnFacilityCollection", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CanCreateHealthProtectionFacilityOnFacilityCollection")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CanCreateHealthProtectionFacilityOnFacilityCollection", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CanCreateHealthProtectionFacilityOnFacilityCollectionResponse")
    @RequestWrapper(localName = "CanCreateHealthProtectionFacilityOnFacilityCollection", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CanCreateHealthProtectionFacilityOnFacilityCollection")
    @ResponseWrapper(localName = "CanCreateHealthProtectionFacilityOnFacilityCollectionResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CanCreateHealthProtectionFacilityOnFacilityCollectionResponse")
    @WebResult(name = "CanCreateHealthProtectionFacilityOnFacilityCollectionResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.Boolean canCreateHealthProtectionFacilityOnFacilityCollection(

        @WebParam(name = "facilityCollectionId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String facilityCollectionId
    );

    @WebMethod(operationName = "SearchCase", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchCase")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchCase", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchCaseResponse")
    @RequestWrapper(localName = "SearchCase", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SearchCase")
    @ResponseWrapper(localName = "SearchCaseResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SearchCaseResponse")
    @WebResult(name = "SearchCaseResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfSearchCaseResultSvcDto searchCase(

        @WebParam(name = "model", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.SearchCaseSvcDto model
    );

    @WebMethod(operationName = "AddDocumentsToFacility", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddDocumentsToFacility")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddDocumentsToFacility", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddDocumentsToFacilityResponse")
    @RequestWrapper(localName = "AddDocumentsToFacility", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddDocumentsToFacility")
    @ResponseWrapper(localName = "AddDocumentsToFacilityResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddDocumentsToFacilityResponse")
    public void addDocumentsToFacility(

        @WebParam(name = "addDocumentToFacilitySvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.AddDocumentsToFacilitySvcDto addDocumentToFacilitySvcDto
    );

    @WebMethod(operationName = "GetDocument", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDocument")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDocument", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDocumentResponse")
    @RequestWrapper(localName = "GetDocument", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDocument")
    @ResponseWrapper(localName = "GetDocumentResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDocumentResponse")
    @WebResult(name = "GetDocumentResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.FileSvcDto getDocument(

        @WebParam(name = "documentId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String documentId
    );

    @WebMethod(operationName = "GetWatchDateTypes", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetWatchDateTypes")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetWatchDateTypes", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetWatchDateTypesResponse")
    @RequestWrapper(localName = "GetWatchDateTypes", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetWatchDateTypes")
    @ResponseWrapper(localName = "GetWatchDateTypesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetWatchDateTypesResponse")
    @WebResult(name = "GetWatchDateTypesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGetWatchDateTypeSvcDto getWatchDateTypes()
;

    @WebMethod(operationName = "CreateCaseWatchDate", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateCaseWatchDate")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateCaseWatchDate", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateCaseWatchDateResponse")
    @RequestWrapper(localName = "CreateCaseWatchDate", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateCaseWatchDate")
    @ResponseWrapper(localName = "CreateCaseWatchDateResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateCaseWatchDateResponse")
    public void createCaseWatchDate(

        @WebParam(name = "createCaseWatchDateSvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.CreateCaseWatchDateSvcDto createCaseWatchDateSvcDto
    );

    @WebMethod(operationName = "CreateRefrigerantFacility", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateRefrigerantFacility")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateRefrigerantFacility", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateRefrigerantFacilityResponse")
    @RequestWrapper(localName = "CreateRefrigerantFacility", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateRefrigerantFacility")
    @ResponseWrapper(localName = "CreateRefrigerantFacilityResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateRefrigerantFacilityResponse")
    @WebResult(name = "CreateRefrigerantFacilityResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String createRefrigerantFacility(

        @WebParam(name = "createRefrigerantFacilitySvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.CreateRefrigerantFacilitySvcDto createRefrigerantFacilitySvcDto
    );

    @WebMethod(operationName = "SetCasePartyRoleContactDetails", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SetCasePartyRoleContactDetails")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SetCasePartyRoleContactDetails", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SetCasePartyRoleContactDetailsResponse")
    @RequestWrapper(localName = "SetCasePartyRoleContactDetails", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SetCasePartyRoleContactDetails")
    @ResponseWrapper(localName = "SetCasePartyRoleContactDetailsResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SetCasePartyRoleContactDetailsResponse")
    public void setCasePartyRoleContactDetails(

        @WebParam(name = "caseId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String caseId,
        @WebParam(name = "connections", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfConnectedRoleSvcDto connections
    );

    @WebMethod(operationName = "CreateOccurrenceOnFacility", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateOccurrenceOnFacility")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateOccurrenceOnFacility", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateOccurrenceOnFacilityResponse")
    @RequestWrapper(localName = "CreateOccurrenceOnFacility", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateOccurrenceOnFacility")
    @ResponseWrapper(localName = "CreateOccurrenceOnFacilityResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateOccurrenceOnFacilityResponse")
    @WebResult(name = "CreateOccurrenceOnFacilityResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String createOccurrenceOnFacility(

        @WebParam(name = "createOccurrenceOnFacilitySvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.CreateOccurrenceOnFacilitySvcDto createOccurrenceOnFacilitySvcDto
    );

    @WebMethod(operationName = "CreateHealthProtectionFacility", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateHealthProtectionFacility")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateHealthProtectionFacility", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateHealthProtectionFacilityResponse")
    @RequestWrapper(localName = "CreateHealthProtectionFacility", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateHealthProtectionFacility")
    @ResponseWrapper(localName = "CreateHealthProtectionFacilityResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateHealthProtectionFacilityResponse")
    @WebResult(name = "CreateHealthProtectionFacilityResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String createHealthProtectionFacility(

        @WebParam(name = "createHealthProtectionFacilitySvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.CreateHealthProtectionFacilitySvcDto createHealthProtectionFacilitySvcDto
    );

    @WebMethod(operationName = "GetBiologicalStepTypes", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetBiologicalStepTypes")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetBiologicalStepTypes", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetBiologicalStepTypesResponse")
    @RequestWrapper(localName = "GetBiologicalStepTypes", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetBiologicalStepTypes")
    @ResponseWrapper(localName = "GetBiologicalStepTypesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetBiologicalStepTypesResponse")
    @WebResult(name = "GetBiologicalStepTypesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getBiologicalStepTypes()
;

    @WebMethod(operationName = "GetWasteWater", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetWasteWater")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetWasteWater", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetWasteWaterResponse")
    @RequestWrapper(localName = "GetWasteWater", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetWasteWater")
    @ResponseWrapper(localName = "GetWasteWaterResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetWasteWaterResponse")
    @WebResult(name = "GetWasteWaterResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getWasteWater()
;

    @WebMethod(operationName = "GetInitators", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetInitators")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetInitators", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetInitatorsResponse")
    @RequestWrapper(localName = "GetInitators", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetInitators")
    @ResponseWrapper(localName = "GetInitatorsResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetInitatorsResponse")
    @WebResult(name = "GetInitatorsResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getInitators()
;

    @WebMethod(operationName = "CreateIndividualSewageFacility", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateIndividualSewageFacility")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateIndividualSewageFacility", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateIndividualSewageFacilityResponse")
    @RequestWrapper(localName = "CreateIndividualSewageFacility", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateIndividualSewageFacility")
    @ResponseWrapper(localName = "CreateIndividualSewageFacilityResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateIndividualSewageFacilityResponse")
    @WebResult(name = "CreateIndividualSewageFacilityResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String createIndividualSewageFacility(

        @WebParam(name = "createIndividualSewageSvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.CreateIndividualSewageFacilitySvcDto createIndividualSewageSvcDto
    );

    @WebMethod(operationName = "GetCase", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetCase")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetCase", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetCaseResponse")
    @RequestWrapper(localName = "GetCase", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetCase")
    @ResponseWrapper(localName = "GetCaseResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetCaseResponse")
    @WebResult(name = "GetCaseResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.CaseSvcDto getCase(

        @WebParam(name = "caseId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String caseId
    );

    @WebMethod(operationName = "SearchFacilityCollection", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchFacilityCollection")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchFacilityCollection", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchFacilityCollectionResponse")
    @RequestWrapper(localName = "SearchFacilityCollection", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SearchFacilityCollection")
    @ResponseWrapper(localName = "SearchFacilityCollectionResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SearchFacilityCollectionResponse")
    @WebResult(name = "SearchFacilityCollectionResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfSearchFacilityCollectioResultSvcDto searchFacilityCollection(

        @WebParam(name = "searchFacilityCollectionSvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.SearchFacilityCollectionSvcDto searchFacilityCollectionSvcDto
    );

    @WebMethod(operationName = "GetDrySolutionTypes", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDrySolutionTypes")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDrySolutionTypes", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDrySolutionTypesResponse")
    @RequestWrapper(localName = "GetDrySolutionTypes", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDrySolutionTypes")
    @ResponseWrapper(localName = "GetDrySolutionTypesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDrySolutionTypesResponse")
    @WebResult(name = "GetDrySolutionTypesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getDrySolutionTypes()
;

    @WebMethod(operationName = "AddFacilityToCase", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddFacilityToCase")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddFacilityToCase", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddFacilityToCaseResponse")
    @RequestWrapper(localName = "AddFacilityToCase", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddFacilityToCase")
    @ResponseWrapper(localName = "AddFacilityToCaseResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddFacilityToCaseResponse")
    public void addFacilityToCase(

        @WebParam(name = "facilityId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String facilityId,
        @WebParam(name = "caseId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String caseId
    );

    @WebMethod(operationName = "GetHandlingOfficerGroups", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetHandlingOfficerGroups")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetHandlingOfficerGroups", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetHandlingOfficerGroupsResponse")
    @RequestWrapper(localName = "GetHandlingOfficerGroups", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetHandlingOfficerGroups")
    @ResponseWrapper(localName = "GetHandlingOfficerGroupsResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetHandlingOfficerGroupsResponse")
    @WebResult(name = "GetHandlingOfficerGroupsResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getHandlingOfficerGroups()
;

    @WebMethod(operationName = "RegisterDocument", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/RegisterDocument")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/RegisterDocument", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/RegisterDocumentResponse")
    @RequestWrapper(localName = "RegisterDocument", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.RegisterDocument")
    @ResponseWrapper(localName = "RegisterDocumentResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.RegisterDocumentResponse")
    @WebResult(name = "RegisterDocumentResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.RegisterDocumentCaseResultSvcDto registerDocument(

        @WebParam(name = "registerDocumentCaseSvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.RegisterDocumentCaseSvcDto registerDocumentCaseSvcDto
    );

    @WebMethod(operationName = "SearchFacility", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchFacility")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchFacility", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchFacilityResponse")
    @RequestWrapper(localName = "SearchFacility", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SearchFacility")
    @ResponseWrapper(localName = "SearchFacilityResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SearchFacilityResponse")
    @WebResult(name = "SearchFacilityResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfSearchFacilityResultSvcDto searchFacility(

        @WebParam(name = "searchFacilitySvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.SearchFacilitySvcDto searchFacilitySvcDto
    );

    @WebMethod(operationName = "ChangeFacilityStatusToActive", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/ChangeFacilityStatusToActive")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/ChangeFacilityStatusToActive", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/ChangeFacilityStatusToActiveResponse")
    @RequestWrapper(localName = "ChangeFacilityStatusToActive", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.ChangeFacilityStatusToActive")
    @ResponseWrapper(localName = "ChangeFacilityStatusToActiveResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.ChangeFacilityStatusToActiveResponse")
    public void changeFacilityStatusToActive(

        @WebParam(name = "facilityId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String facilityId,
        @WebParam(name = "startDate", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.time.LocalDateTime startDate
    );

    @WebMethod(operationName = "CreateOrganizationParty", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateOrganizationParty")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateOrganizationParty", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/CreateOrganizationPartyResponse")
    @RequestWrapper(localName = "CreateOrganizationParty", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateOrganizationParty")
    @ResponseWrapper(localName = "CreateOrganizationPartyResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.CreateOrganizationPartyResponse")
    @WebResult(name = "CreateOrganizationPartyResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String createOrganizationParty(

        @WebParam(name = "organizationParty", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.OrganizationSvcDto organizationParty
    );

    @WebMethod(operationName = "GetRefrigerants", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetRefrigerants")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetRefrigerants", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetRefrigerantsResponse")
    @RequestWrapper(localName = "GetRefrigerants", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetRefrigerants")
    @ResponseWrapper(localName = "GetRefrigerantsResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetRefrigerantsResponse")
    @WebResult(name = "GetRefrigerantsResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getRefrigerants()
;

    @WebMethod(operationName = "AddEstateToCase", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddEstateToCase")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddEstateToCase", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddEstateToCaseResponse")
    @RequestWrapper(localName = "AddEstateToCase", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddEstateToCase")
    @ResponseWrapper(localName = "AddEstateToCaseResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddEstateToCaseResponse")
    @WebResult(name = "AddEstateToCaseResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public java.lang.String addEstateToCase(

        @WebParam(name = "addEstateToCaseSvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.AddEstateToCaseSvcDto addEstateToCaseSvcDto
    );

    @WebMethod(operationName = "SetFacilityPartyRoleContactDetails", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SetFacilityPartyRoleContactDetails")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SetFacilityPartyRoleContactDetails", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SetFacilityPartyRoleContactDetailsResponse")
    @RequestWrapper(localName = "SetFacilityPartyRoleContactDetails", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SetFacilityPartyRoleContactDetails")
    @ResponseWrapper(localName = "SetFacilityPartyRoleContactDetailsResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SetFacilityPartyRoleContactDetailsResponse")
    public void setFacilityPartyRoleContactDetails(

        @WebParam(name = "facilityId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String facilityId,
        @WebParam(name = "connections", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfConnectedRoleSvcDto connections
    );

    @WebMethod(operationName = "GetContactDetailPathsAndTypes", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetContactDetailPathsAndTypes")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetContactDetailPathsAndTypes", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetContactDetailPathsAndTypesResponse")
    @RequestWrapper(localName = "GetContactDetailPathsAndTypes", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetContactDetailPathsAndTypes")
    @ResponseWrapper(localName = "GetContactDetailPathsAndTypesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetContactDetailPathsAndTypesResponse")
    @WebResult(name = "GetContactDetailPathsAndTypesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGetContactDetailPathsAndTypesSvcDto getContactDetailPathsAndTypes()
;

    @WebMethod(operationName = "SearchParty", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchParty")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchParty", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/SearchPartyResponse")
    @RequestWrapper(localName = "SearchParty", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SearchParty")
    @ResponseWrapper(localName = "SearchPartyResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.SearchPartyResponse")
    @WebResult(name = "SearchPartyResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfPartySvcDto searchParty(

        @WebParam(name = "model", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.SearchPartySvcDto model
    );

    @WebMethod(operationName = "GetCaseStatuses", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetCaseStatuses")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetCaseStatuses", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetCaseStatusesResponse")
    @RequestWrapper(localName = "GetCaseStatuses", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetCaseStatuses")
    @ResponseWrapper(localName = "GetCaseStatusesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetCaseStatusesResponse")
    @WebResult(name = "GetCaseStatusesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getCaseStatuses()
;

    @WebMethod(operationName = "GetAddressTypes", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetAddressTypes")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetAddressTypes", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetAddressTypesResponse")
    @RequestWrapper(localName = "GetAddressTypes", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetAddressTypes")
    @ResponseWrapper(localName = "GetAddressTypesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetAddressTypesResponse")
    @WebResult(name = "GetAddressTypesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getAddressTypes()
;

    @WebMethod(operationName = "GetDiaryPlan", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDiaryPlan")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDiaryPlan", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDiaryPlanResponse")
    @RequestWrapper(localName = "GetDiaryPlan", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDiaryPlan")
    @ResponseWrapper(localName = "GetDiaryPlanResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDiaryPlanResponse")
    @WebResult(name = "GetDiaryPlanResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfDiaryPlanSvcDto getDiaryPlan()
;

    @WebMethod(operationName = "GetHeatTransferFluidTypes", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetHeatTransferFluidTypes")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetHeatTransferFluidTypes", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetHeatTransferFluidTypesResponse")
    @RequestWrapper(localName = "GetHeatTransferFluidTypes", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetHeatTransferFluidTypes")
    @ResponseWrapper(localName = "GetHeatTransferFluidTypesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetHeatTransferFluidTypesResponse")
    @WebResult(name = "GetHeatTransferFluidTypesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getHeatTransferFluidTypes()
;

    @WebMethod(operationName = "AddDocumentsToCase", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddDocumentsToCase")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddDocumentsToCase", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddDocumentsToCaseResponse")
    @RequestWrapper(localName = "AddDocumentsToCase", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddDocumentsToCase")
    @ResponseWrapper(localName = "AddDocumentsToCaseResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddDocumentsToCaseResponse")
    public void addDocumentsToCase(

        @WebParam(name = "addDocumentToCaseSvcDto", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.AddDocumentsToCaseSvcDto addDocumentToCaseSvcDto
    );

    @WebMethod(operationName = "GetFacilityStatuses", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetFacilityStatuses")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetFacilityStatuses", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetFacilityStatusesResponse")
    @RequestWrapper(localName = "GetFacilityStatuses", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetFacilityStatuses")
    @ResponseWrapper(localName = "GetFacilityStatusesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetFacilityStatusesResponse")
    @WebResult(name = "GetFacilityStatusesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getFacilityStatuses()
;

    @WebMethod(operationName = "GetProcessTypes", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetProcessTypes")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetProcessTypes", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetProcessTypesResponse")
    @RequestWrapper(localName = "GetProcessTypes", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetProcessTypes")
    @ResponseWrapper(localName = "GetProcessTypesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetProcessTypesResponse")
    @WebResult(name = "GetProcessTypesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getProcessTypes()
;

    @WebMethod(operationName = "GetDocumentStatuses", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDocumentStatuses")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDocumentStatuses", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetDocumentStatusesResponse")
    @RequestWrapper(localName = "GetDocumentStatuses", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDocumentStatuses")
    @ResponseWrapper(localName = "GetDocumentStatusesResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetDocumentStatusesResponse")
    @WebResult(name = "GetDocumentStatusesResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto getDocumentStatuses()
;

    @WebMethod(operationName = "GetParty", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetParty")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetParty", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/GetPartyResponse")
    @RequestWrapper(localName = "GetParty", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetParty")
    @ResponseWrapper(localName = "GetPartyResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.GetPartyResponse")
    @WebResult(name = "GetPartyResult", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
    public v1.datacontracts.minutmiljo.api.ecos.PartySvcDto getParty(

        @WebParam(name = "partyId", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        java.lang.String partyId
    );

    @WebMethod(operationName = "AddPartyToCase", action = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddPartyToCase")
    @Action(input = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddPartyToCase", output = "urn:Ecos.API.MinutMiljo.Service.V1/IMinutMiljoService/AddPartyToCaseResponse")
    @RequestWrapper(localName = "AddPartyToCase", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddPartyToCase")
    @ResponseWrapper(localName = "AddPartyToCaseResponse", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1", className = "v1.service.minutmiljo.api.ecos.AddPartyToCaseResponse")
    public void addPartyToCase(

        @WebParam(name = "model", targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
        v1.datacontracts.minutmiljo.api.ecos.AddPartyToCaseSvcDto model
    );
}
