
package v1.service.minutmiljo.api.ecos;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-10-20T15:30:01.867+02:00
 * Generated source version: 3.4.2
 *
 */
public final class IMinutMiljoService_BasicHttpBindingIMinutMiljoService_Client {

    private static final QName SERVICE_NAME = new QName("urn:Ecos.API.MinutMiljo.Service.V1", "MinutMiljoService");

    private IMinutMiljoService_BasicHttpBindingIMinutMiljoService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MinutMiljoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MinutMiljoService ss = new MinutMiljoService(wsdlURL, SERVICE_NAME);
        IMinutMiljoService port = ss.getBasicHttpBindingIMinutMiljoService();

        {
        System.out.println("Invoking getAccommodationTypes...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getAccommodationTypes__return = port.getAccommodationTypes();
        System.out.println("getAccommodationTypes.result=" + _getAccommodationTypes__return);


        }
        {
        System.out.println("Invoking createOccurrenceOnCase...");
        v1.datacontracts.minutmiljo.api.ecos.CreateOccurrenceOnCaseSvcDto _createOccurrenceOnCase_createOccurrenceOnCaseSvcDto = null;
        java.lang.String _createOccurrenceOnCase__return = port.createOccurrenceOnCase(_createOccurrenceOnCase_createOccurrenceOnCaseSvcDto);
        System.out.println("createOccurrenceOnCase.result=" + _createOccurrenceOnCase__return);


        }
        {
        System.out.println("Invoking getDrySolutionCompostTypes...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getDrySolutionCompostTypes__return = port.getDrySolutionCompostTypes();
        System.out.println("getDrySolutionCompostTypes.result=" + _getDrySolutionCompostTypes__return);


        }
        {
        System.out.println("Invoking createPersonParty...");
        v1.datacontracts.minutmiljo.api.ecos.PersonSvcDto _createPersonParty_personParty = null;
        java.lang.String _createPersonParty__return = port.createPersonParty(_createPersonParty_personParty);
        System.out.println("createPersonParty.result=" + _createPersonParty__return);


        }
        {
        System.out.println("Invoking createFoodFacility...");
        v1.datacontracts.minutmiljo.api.ecos.CreateFoodFacilitySvcDto _createFoodFacility_createFoodFacilitySvcDto = null;
        java.lang.String _createFoodFacility__return = port.createFoodFacility(_createFoodFacility_createFoodFacilitySvcDto);
        System.out.println("createFoodFacility.result=" + _createFoodFacility__return);


        }
        {
        System.out.println("Invoking getFoodFacilities...");
        v1.datacontracts.minutmiljo.api.ecos.GetFoodFacilitiesSvcDto _getFoodFacilities_request = null;
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfFoodFacilityInfoSvcDto _getFoodFacilities__return = port.getFoodFacilities(_getFoodFacilities_request);
        System.out.println("getFoodFacilities.result=" + _getFoodFacilities__return);


        }
        {
        System.out.println("Invoking getRefrigerantUnitUsages...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getRefrigerantUnitUsages__return = port.getRefrigerantUnitUsages();
        System.out.println("getRefrigerantUnitUsages.result=" + _getRefrigerantUnitUsages__return);


        }
        {
        System.out.println("Invoking getCasePartyRoles...");
        java.lang.String _getCasePartyRoles_caseId = "";
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfConnectedRoleSvcDto _getCasePartyRoles__return = port.getCasePartyRoles(_getCasePartyRoles_caseId);
        System.out.println("getCasePartyRoles.result=" + _getCasePartyRoles__return);


        }
        {
        System.out.println("Invoking getFacilityPartyRoles...");
        java.lang.String _getFacilityPartyRoles_facilityId = "";
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfConnectedRoleSvcDto _getFacilityPartyRoles__return = port.getFacilityPartyRoles(_getFacilityPartyRoles_facilityId);
        System.out.println("getFacilityPartyRoles.result=" + _getFacilityPartyRoles__return);


        }
        {
        System.out.println("Invoking createHeatPumpFacility...");
        v1.datacontracts.minutmiljo.api.ecos.CreateHeatPumpFacilitySvcDto _createHeatPumpFacility_createIndividualSewageSvcDto = null;
        java.lang.String _createHeatPumpFacility__return = port.createHeatPumpFacility(_createHeatPumpFacility_createIndividualSewageSvcDto);
        System.out.println("createHeatPumpFacility.result=" + _createHeatPumpFacility__return);


        }
        {
        System.out.println("Invoking addPartyToFacility...");
        v1.datacontracts.minutmiljo.api.ecos.AddPartyToFacilitySvcDto _addPartyToFacility_model = null;
        port.addPartyToFacility(_addPartyToFacility_model);


        }
        {
        System.out.println("Invoking canCreateHealthProtectionFacilityOnFacilityCollection...");
        java.lang.String _canCreateHealthProtectionFacilityOnFacilityCollection_facilityCollectionId = "";
        java.lang.Boolean _canCreateHealthProtectionFacilityOnFacilityCollection__return = port.canCreateHealthProtectionFacilityOnFacilityCollection(_canCreateHealthProtectionFacilityOnFacilityCollection_facilityCollectionId);
        System.out.println("canCreateHealthProtectionFacilityOnFacilityCollection.result=" + _canCreateHealthProtectionFacilityOnFacilityCollection__return);


        }
        {
        System.out.println("Invoking searchCase...");
        v1.datacontracts.minutmiljo.api.ecos.SearchCaseSvcDto _searchCase_model = null;
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfSearchCaseResultSvcDto _searchCase__return = port.searchCase(_searchCase_model);
        System.out.println("searchCase.result=" + _searchCase__return);


        }
        {
        System.out.println("Invoking addDocumentsToFacility...");
        v1.datacontracts.minutmiljo.api.ecos.AddDocumentsToFacilitySvcDto _addDocumentsToFacility_addDocumentToFacilitySvcDto = null;
        port.addDocumentsToFacility(_addDocumentsToFacility_addDocumentToFacilitySvcDto);


        }
        {
        System.out.println("Invoking getDocument...");
        java.lang.String _getDocument_documentId = "";
        v1.datacontracts.minutmiljo.api.ecos.FileSvcDto _getDocument__return = port.getDocument(_getDocument_documentId);
        System.out.println("getDocument.result=" + _getDocument__return);


        }
        {
        System.out.println("Invoking getWatchDateTypes...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGetWatchDateTypeSvcDto _getWatchDateTypes__return = port.getWatchDateTypes();
        System.out.println("getWatchDateTypes.result=" + _getWatchDateTypes__return);


        }
        {
        System.out.println("Invoking createCaseWatchDate...");
        v1.datacontracts.minutmiljo.api.ecos.CreateCaseWatchDateSvcDto _createCaseWatchDate_createCaseWatchDateSvcDto = null;
        port.createCaseWatchDate(_createCaseWatchDate_createCaseWatchDateSvcDto);


        }
        {
        System.out.println("Invoking createRefrigerantFacility...");
        v1.datacontracts.minutmiljo.api.ecos.CreateRefrigerantFacilitySvcDto _createRefrigerantFacility_createRefrigerantFacilitySvcDto = null;
        java.lang.String _createRefrigerantFacility__return = port.createRefrigerantFacility(_createRefrigerantFacility_createRefrigerantFacilitySvcDto);
        System.out.println("createRefrigerantFacility.result=" + _createRefrigerantFacility__return);


        }
        {
        System.out.println("Invoking setCasePartyRoleContactDetails...");
        java.lang.String _setCasePartyRoleContactDetails_caseId = "";
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfConnectedRoleSvcDto _setCasePartyRoleContactDetails_connections = null;
        port.setCasePartyRoleContactDetails(_setCasePartyRoleContactDetails_caseId, _setCasePartyRoleContactDetails_connections);


        }
        {
        System.out.println("Invoking createOccurrenceOnFacility...");
        v1.datacontracts.minutmiljo.api.ecos.CreateOccurrenceOnFacilitySvcDto _createOccurrenceOnFacility_createOccurrenceOnFacilitySvcDto = null;
        java.lang.String _createOccurrenceOnFacility__return = port.createOccurrenceOnFacility(_createOccurrenceOnFacility_createOccurrenceOnFacilitySvcDto);
        System.out.println("createOccurrenceOnFacility.result=" + _createOccurrenceOnFacility__return);


        }
        {
        System.out.println("Invoking createHealthProtectionFacility...");
        v1.datacontracts.minutmiljo.api.ecos.CreateHealthProtectionFacilitySvcDto _createHealthProtectionFacility_createHealthProtectionFacilitySvcDto = null;
        java.lang.String _createHealthProtectionFacility__return = port.createHealthProtectionFacility(_createHealthProtectionFacility_createHealthProtectionFacilitySvcDto);
        System.out.println("createHealthProtectionFacility.result=" + _createHealthProtectionFacility__return);


        }
        {
        System.out.println("Invoking getBiologicalStepTypes...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getBiologicalStepTypes__return = port.getBiologicalStepTypes();
        System.out.println("getBiologicalStepTypes.result=" + _getBiologicalStepTypes__return);


        }
        {
        System.out.println("Invoking getWasteWater...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getWasteWater__return = port.getWasteWater();
        System.out.println("getWasteWater.result=" + _getWasteWater__return);


        }
        {
        System.out.println("Invoking getInitators...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getInitators__return = port.getInitators();
        System.out.println("getInitators.result=" + _getInitators__return);


        }
        {
        System.out.println("Invoking createIndividualSewageFacility...");
        v1.datacontracts.minutmiljo.api.ecos.CreateIndividualSewageFacilitySvcDto _createIndividualSewageFacility_createIndividualSewageSvcDto = null;
        java.lang.String _createIndividualSewageFacility__return = port.createIndividualSewageFacility(_createIndividualSewageFacility_createIndividualSewageSvcDto);
        System.out.println("createIndividualSewageFacility.result=" + _createIndividualSewageFacility__return);


        }
        {
        System.out.println("Invoking getCase...");
        java.lang.String _getCase_caseId = "";
        v1.datacontracts.minutmiljo.api.ecos.CaseSvcDto _getCase__return = port.getCase(_getCase_caseId);
        System.out.println("getCase.result=" + _getCase__return);


        }
        {
        System.out.println("Invoking searchFacilityCollection...");
        v1.datacontracts.minutmiljo.api.ecos.SearchFacilityCollectionSvcDto _searchFacilityCollection_searchFacilityCollectionSvcDto = null;
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfSearchFacilityCollectioResultSvcDto _searchFacilityCollection__return = port.searchFacilityCollection(_searchFacilityCollection_searchFacilityCollectionSvcDto);
        System.out.println("searchFacilityCollection.result=" + _searchFacilityCollection__return);


        }
        {
        System.out.println("Invoking getDrySolutionTypes...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getDrySolutionTypes__return = port.getDrySolutionTypes();
        System.out.println("getDrySolutionTypes.result=" + _getDrySolutionTypes__return);


        }
        {
        System.out.println("Invoking addFacilityToCase...");
        java.lang.String _addFacilityToCase_facilityId = "";
        java.lang.String _addFacilityToCase_caseId = "";
        port.addFacilityToCase(_addFacilityToCase_facilityId, _addFacilityToCase_caseId);


        }
        {
        System.out.println("Invoking getHandlingOfficerGroups...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getHandlingOfficerGroups__return = port.getHandlingOfficerGroups();
        System.out.println("getHandlingOfficerGroups.result=" + _getHandlingOfficerGroups__return);


        }
        {
        System.out.println("Invoking registerDocument...");
        v1.datacontracts.minutmiljo.api.ecos.RegisterDocumentCaseSvcDto _registerDocument_registerDocumentCaseSvcDto = null;
        v1.datacontracts.minutmiljo.api.ecos.RegisterDocumentCaseResultSvcDto _registerDocument__return = port.registerDocument(_registerDocument_registerDocumentCaseSvcDto);
        System.out.println("registerDocument.result=" + _registerDocument__return);


        }
        {
        System.out.println("Invoking searchFacility...");
        v1.datacontracts.minutmiljo.api.ecos.SearchFacilitySvcDto _searchFacility_searchFacilitySvcDto = null;
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfSearchFacilityResultSvcDto _searchFacility__return = port.searchFacility(_searchFacility_searchFacilitySvcDto);
        System.out.println("searchFacility.result=" + _searchFacility__return);


        }
        {
        System.out.println("Invoking changeFacilityStatusToActive...");
        java.lang.String _changeFacilityStatusToActive_facilityId = "";
        java.time.LocalDateTime _changeFacilityStatusToActive_startDate = null;
        port.changeFacilityStatusToActive(_changeFacilityStatusToActive_facilityId, _changeFacilityStatusToActive_startDate);


        }
        {
        System.out.println("Invoking createOrganizationParty...");
        v1.datacontracts.minutmiljo.api.ecos.OrganizationSvcDto _createOrganizationParty_organizationParty = null;
        java.lang.String _createOrganizationParty__return = port.createOrganizationParty(_createOrganizationParty_organizationParty);
        System.out.println("createOrganizationParty.result=" + _createOrganizationParty__return);


        }
        {
        System.out.println("Invoking getRefrigerants...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getRefrigerants__return = port.getRefrigerants();
        System.out.println("getRefrigerants.result=" + _getRefrigerants__return);


        }
        {
        System.out.println("Invoking addEstateToCase...");
        v1.datacontracts.minutmiljo.api.ecos.AddEstateToCaseSvcDto _addEstateToCase_addEstateToCaseSvcDto = null;
        java.lang.String _addEstateToCase__return = port.addEstateToCase(_addEstateToCase_addEstateToCaseSvcDto);
        System.out.println("addEstateToCase.result=" + _addEstateToCase__return);


        }
        {
        System.out.println("Invoking setFacilityPartyRoleContactDetails...");
        java.lang.String _setFacilityPartyRoleContactDetails_facilityId = "";
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfConnectedRoleSvcDto _setFacilityPartyRoleContactDetails_connections = null;
        port.setFacilityPartyRoleContactDetails(_setFacilityPartyRoleContactDetails_facilityId, _setFacilityPartyRoleContactDetails_connections);


        }
        {
        System.out.println("Invoking getContactDetailPathsAndTypes...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGetContactDetailPathsAndTypesSvcDto _getContactDetailPathsAndTypes__return = port.getContactDetailPathsAndTypes();
        System.out.println("getContactDetailPathsAndTypes.result=" + _getContactDetailPathsAndTypes__return);


        }
        {
        System.out.println("Invoking searchParty...");
        v1.datacontracts.minutmiljo.api.ecos.SearchPartySvcDto _searchParty_model = null;
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfPartySvcDto _searchParty__return = port.searchParty(_searchParty_model);
        System.out.println("searchParty.result=" + _searchParty__return);


        }
        {
        System.out.println("Invoking getCaseStatuses...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getCaseStatuses__return = port.getCaseStatuses();
        System.out.println("getCaseStatuses.result=" + _getCaseStatuses__return);


        }
        {
        System.out.println("Invoking getAddressTypes...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getAddressTypes__return = port.getAddressTypes();
        System.out.println("getAddressTypes.result=" + _getAddressTypes__return);


        }
        {
        System.out.println("Invoking getDiaryPlan...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfDiaryPlanSvcDto _getDiaryPlan__return = port.getDiaryPlan();
        System.out.println("getDiaryPlan.result=" + _getDiaryPlan__return);


        }
        {
        System.out.println("Invoking getHeatTransferFluidTypes...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getHeatTransferFluidTypes__return = port.getHeatTransferFluidTypes();
        System.out.println("getHeatTransferFluidTypes.result=" + _getHeatTransferFluidTypes__return);


        }
        {
        System.out.println("Invoking addDocumentsToCase...");
        v1.datacontracts.minutmiljo.api.ecos.AddDocumentsToCaseSvcDto _addDocumentsToCase_addDocumentToCaseSvcDto = null;
        port.addDocumentsToCase(_addDocumentsToCase_addDocumentToCaseSvcDto);


        }
        {
        System.out.println("Invoking getFacilityStatuses...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getFacilityStatuses__return = port.getFacilityStatuses();
        System.out.println("getFacilityStatuses.result=" + _getFacilityStatuses__return);


        }
        {
        System.out.println("Invoking getProcessTypes...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getProcessTypes__return = port.getProcessTypes();
        System.out.println("getProcessTypes.result=" + _getProcessTypes__return);


        }
        {
        System.out.println("Invoking getDocumentStatuses...");
        v1.datacontracts.minutmiljo.api.ecos.ArrayOfGuidNamePairSvcDto _getDocumentStatuses__return = port.getDocumentStatuses();
        System.out.println("getDocumentStatuses.result=" + _getDocumentStatuses__return);


        }
        {
        System.out.println("Invoking getParty...");
        java.lang.String _getParty_partyId = "";
        v1.datacontracts.minutmiljo.api.ecos.PartySvcDto _getParty__return = port.getParty(_getParty_partyId);
        System.out.println("getParty.result=" + _getParty__return);


        }
        {
        System.out.println("Invoking addPartyToCase...");
        v1.datacontracts.minutmiljo.api.ecos.AddPartyToCaseSvcDto _addPartyToCase_model = null;
        port.addPartyToCase(_addPartyToCase_model);


        }

        System.exit(0);
    }

}
