package v1.service.minutmiljo.api.ecos;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-10-20T15:30:02.016+02:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "MinutMiljoService",
                  wsdlLocation = "classpath:WEB-INF/saas730_MinutMiljoService.xml",
                  targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V1")
public class MinutMiljoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:Ecos.API.MinutMiljo.Service.V1", "MinutMiljoService");
    public final static QName BasicHttpBindingIMinutMiljoService = new QName("urn:Ecos.API.MinutMiljo.Service.V1", "BasicHttpBinding_IMinutMiljoService");
    public final static QName BasicHttpBindingIMinutMiljoService1 = new QName("urn:Ecos.API.MinutMiljo.Service.V1", "BasicHttpBinding_IMinutMiljoService1");
    static {
        URL url = MinutMiljoService.class.getClassLoader().getResource("WEB-INF/saas730_MinutMiljoService.xml");
        if (url == null) {
            java.util.logging.Logger.getLogger(MinutMiljoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:WEB-INF/saas730_MinutMiljoService.xml");
        }
        WSDL_LOCATION = url;
    }

    public MinutMiljoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MinutMiljoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MinutMiljoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MinutMiljoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MinutMiljoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MinutMiljoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IMinutMiljoService
     */
    @WebEndpoint(name = "BasicHttpBinding_IMinutMiljoService")
    public IMinutMiljoService getBasicHttpBindingIMinutMiljoService() {
        return super.getPort(BasicHttpBindingIMinutMiljoService, IMinutMiljoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMinutMiljoService
     */
    @WebEndpoint(name = "BasicHttpBinding_IMinutMiljoService")
    public IMinutMiljoService getBasicHttpBindingIMinutMiljoService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIMinutMiljoService, IMinutMiljoService.class, features);
    }


    /**
     *
     * @return
     *     returns IMinutMiljoService
     */
    @WebEndpoint(name = "BasicHttpBinding_IMinutMiljoService1")
    public IMinutMiljoService getBasicHttpBindingIMinutMiljoService1() {
        return super.getPort(BasicHttpBindingIMinutMiljoService1, IMinutMiljoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMinutMiljoService
     */
    @WebEndpoint(name = "BasicHttpBinding_IMinutMiljoService1")
    public IMinutMiljoService getBasicHttpBindingIMinutMiljoService1(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIMinutMiljoService1, IMinutMiljoService.class, features);
    }

}
