
package v2.service.minutmiljo.api.ecos;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-10-20T15:30:02.544+02:00
 * Generated source version: 3.4.2
 *
 */
public final class IMinutMiljoServiceV2_BasicHttpBindingIMinutMiljoServiceV2_Client {

    private static final QName SERVICE_NAME = new QName("urn:Ecos.API.MinutMiljo.Service.V2", "MinutMiljoServiceV2");

    private IMinutMiljoServiceV2_BasicHttpBindingIMinutMiljoServiceV2_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MinutMiljoServiceV2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MinutMiljoServiceV2 ss = new MinutMiljoServiceV2(wsdlURL, SERVICE_NAME);
        IMinutMiljoServiceV2 port = ss.getBasicHttpBindingIMinutMiljoServiceV2();

        {
        System.out.println("Invoking registerDocument...");
        v2.datacontracts.minutmiljo.api.ecos.RegisterDocumentCaseSvcDtoV2 _registerDocument_registerDocumentCaseSvcDto = null;
        v1.datacontracts.minutmiljo.api.ecos.RegisterDocumentCaseResultSvcDto _registerDocument__return = port.registerDocument(_registerDocument_registerDocumentCaseSvcDto);
        System.out.println("registerDocument.result=" + _registerDocument__return);


        }

        System.exit(0);
    }

}
