package v2.service.minutmiljo.api.ecos;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-10-20T15:30:02.564+02:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "MinutMiljoServiceV2",
                  wsdlLocation = "classpath:WEB-INF/saas730_MinutMiljoServiceV2.xml",
                  targetNamespace = "urn:Ecos.API.MinutMiljo.Service.V2")
public class MinutMiljoServiceV2 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:Ecos.API.MinutMiljo.Service.V2", "MinutMiljoServiceV2");
    public final static QName BasicHttpBindingIMinutMiljoServiceV2 = new QName("urn:Ecos.API.MinutMiljo.Service.V2", "BasicHttpBinding_IMinutMiljoServiceV2");
    public final static QName BasicHttpBindingIMinutMiljoServiceV21 = new QName("urn:Ecos.API.MinutMiljo.Service.V2", "BasicHttpBinding_IMinutMiljoServiceV21");
    static {
        URL url = MinutMiljoServiceV2.class.getClassLoader().getResource("WEB-INF/saas730_MinutMiljoServiceV2.xml");
        if (url == null) {
            java.util.logging.Logger.getLogger(MinutMiljoServiceV2.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:WEB-INF/saas730_MinutMiljoServiceV2.xml");
        }
        WSDL_LOCATION = url;
    }

    public MinutMiljoServiceV2(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MinutMiljoServiceV2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MinutMiljoServiceV2() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MinutMiljoServiceV2(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MinutMiljoServiceV2(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MinutMiljoServiceV2(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IMinutMiljoServiceV2
     */
    @WebEndpoint(name = "BasicHttpBinding_IMinutMiljoServiceV2")
    public IMinutMiljoServiceV2 getBasicHttpBindingIMinutMiljoServiceV2() {
        return super.getPort(BasicHttpBindingIMinutMiljoServiceV2, IMinutMiljoServiceV2.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMinutMiljoServiceV2
     */
    @WebEndpoint(name = "BasicHttpBinding_IMinutMiljoServiceV2")
    public IMinutMiljoServiceV2 getBasicHttpBindingIMinutMiljoServiceV2(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIMinutMiljoServiceV2, IMinutMiljoServiceV2.class, features);
    }


    /**
     *
     * @return
     *     returns IMinutMiljoServiceV2
     */
    @WebEndpoint(name = "BasicHttpBinding_IMinutMiljoServiceV21")
    public IMinutMiljoServiceV2 getBasicHttpBindingIMinutMiljoServiceV21() {
        return super.getPort(BasicHttpBindingIMinutMiljoServiceV21, IMinutMiljoServiceV2.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMinutMiljoServiceV2
     */
    @WebEndpoint(name = "BasicHttpBinding_IMinutMiljoServiceV21")
    public IMinutMiljoServiceV2 getBasicHttpBindingIMinutMiljoServiceV21(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIMinutMiljoServiceV21, IMinutMiljoServiceV2.class, features);
    }

}
